In [67]:
import numpy as np
from single_head_attention import attention

In [ ]:
def multihead_attention(X, W_Q, W_K, W_V, W_O, num_heads):
    Q = np.dot(X, W_Q)
    V = np.dot(X, W_V)
    K = np.dot(X, W_K)

    dim_k = K.shape[-1] // num_heads

    list_Q = []
    list_V = []
    list_K = []

    for i in range(0, Q.shape[1], dim_k):
        list_Q.append(Q[:, i:i+dim_k])
        list_K.append(K[:, i:i+dim_k])
        list_V.append(V[:, i:i+dim_k])

    slices_with_attention = []

    for i in range(len(list_Q)):
        slices_with_attention.append(attention(list_Q[i], list_K[i], list_V[i]))

    concatenated = np.concatenate(slices_with_attention, axis=1)

    return np.dot(concatenated, W_O)


In [ ]:
d_model=4
num_heads=2

X = np.array([
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [1, 1, 0, 0]
])

np.random.seed(42)
W_Q = np.random.randn(d_model, d_model)
W_K = np.random.randn(d_model, d_model)
W_V = np.random.randn(d_model, d_model)
W_O = np.random.randn(d_model, d_model)

print(multihead_attention(X, W_Q, W_K, W_V, W_O, num_heads))

[[ 2.18367596 -0.97177056 -3.23226502 -3.81746792]
 [ 2.10409842 -0.19575074 -2.60715417 -2.24454717]
 [ 2.40933696 -0.57182511 -4.52577478 -5.29836959]]
