In [1]:
import numpy as np

In [ ]:

def positional_encoding(X):
    d_model = X.shape[-1]

    starting_matrix = np.zeros((X.shape[0], X.shape[1]))

    encoded_matrix = []

    position = 0

    for row in starting_matrix:

        final_row_encode = np.copy(row)

        for i in range(0, len(row), 2):

            final_row_encode[i] = np.sin(np.divide(position, np.power(10000, np.divide(np.multiply(2, i), d_model))))
        
            final_row_encode[i + 1] = np.cos(
                np.divide(
                    position, 
                    np.power(
                        10000, 
                        np.divide(
                            np.multiply(2, i), 
                            d_model
                        )
                    )
                )
            )

        position += 1

        encoded_matrix.append(final_row_encode)

    return X + encoded_matrix

In [9]:
X = np.array([
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [1, 1, 0, 0]
])

print(positional_encoding(X))

[[1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [8.41470985e-01 1.54030231e+00 9.99999998e-05 2.00000000e+00]
 [1.90929743e+00 5.83853163e-01 1.99999999e-04 9.99999980e-01]]
